CREATE TYPE "public"."audit_category" AS ENUM('mutation', 'read');--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'start';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'cancel';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'retry';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'subscribe';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'unsubscribe';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'complete';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'uncomplete';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'move';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'reprocess';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'upload';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'download';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'redact';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'invite';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'accept';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'reject';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'mark_read';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'generate';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'login';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'logout';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'verify';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'reset';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'list';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'get';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'search';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'detect';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'apply';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'check';--> statement-breakpoint
ALTER TYPE "public"."audit_resource_type" ADD VALUE 'meeting';--> statement-breakpoint
ALTER TYPE "public"."audit_resource_type" ADD VALUE 'bot_session';--> statement-breakpoint
ALTER TYPE "public"."audit_resource_type" ADD VALUE 'bot_settings';--> statement-breakpoint
ALTER TYPE "public"."audit_resource_type" ADD VALUE 'bot_subscription';--> statement-breakpoint
ALTER TYPE "public"."audit_resource_type" ADD VALUE 'notification';--> statement-breakpoint
ALTER TYPE "public"."audit_resource_type" ADD VALUE 'team';--> statement-breakpoint
ALTER TYPE "public"."audit_resource_type" ADD VALUE 'onboarding';--> statement-breakpoint
ALTER TYPE "public"."audit_resource_type" ADD VALUE 'auto_action';--> statement-breakpoint
ALTER TYPE "public"."audit_resource_type" ADD VALUE 'agenda';--> statement-breakpoint
ALTER TYPE "public"."audit_resource_type" ADD VALUE 'agenda_template';--> statement-breakpoint
ALTER TYPE "public"."audit_resource_type" ADD VALUE 'share_token';--> statement-breakpoint
ALTER TYPE "public"."audit_resource_type" ADD VALUE 'drive_watch';--> statement-breakpoint
ALTER TYPE "public"."audit_resource_type" ADD VALUE 'knowledge_base_document';--> statement-breakpoint
ALTER TYPE "public"."audit_resource_type" ADD VALUE 'project_template';--> statement-breakpoint
ALTER TYPE "public"."audit_resource_type" ADD VALUE 'redaction';--> statement-breakpoint
ALTER TYPE "public"."audit_resource_type" ADD VALUE 'privacy_request';--> statement-breakpoint
ALTER TYPE "public"."audit_resource_type" ADD VALUE 'data_export';--> statement-breakpoint
ALTER TYPE "public"."audit_resource_type" ADD VALUE 'invitation';--> statement-breakpoint
ALTER TYPE "public"."audit_resource_type" ADD VALUE 'calendar';--> statement-breakpoint
ALTER TYPE "public"."audit_resource_type" ADD VALUE 'audit_log';--> statement-breakpoint
ALTER TYPE "public"."audit_resource_type" ADD VALUE 'blob';--> statement-breakpoint
ALTER TABLE "audit_logs" ALTER COLUMN "event_type" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "audit_logs" ALTER COLUMN "resource_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "audit_logs" ADD COLUMN "category" "audit_category" NOT NULL;--> statement-breakpoint
DROP TYPE "public"."audit_event_type";